{
 "title": "Movie_Rec",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "CPU Utilisation",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 9, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"flask_app\"}[1m])*100",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "meminfo_memtotal{job=\"flask_app\"}",
     "legendFormat": "Installed"
    },
    {
     "expr": "meminfo_memtotal - meminfo_memavailable ",
     "legendFormat": "Used"
    },
    { "expr": "meminfo_memavailable", "legendFormat": "Available" },
    {
     "expr": "meminfo_swaptotal  - meminfo_swapfree",
     "legendFormat": "Swap"
    }
   ]
  },
  {
   "title": "Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 7, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(flask_http_request_total{method=\"GET\"}[1m])",
     "legendFormat": "{{method}}"
    }
   ]
  }
 ]
}